NiceNode/nice-node

src/__tests__/node/geth.test.ts

Wasn't sure if this is enough to resolve jgresham/nice-node#15; please feel free to let me know if it should be improved upon, like checking logs, or pid. Thanks!

Test: Start and stop geth

---

src/common/NodeSpecs/geth/geth-v1.0.0.json

fix: geth http api capitalization

---

src/renderer/Presentational/AddEthereumNode/AddEthereumNode.tsx

we will add this functionality back soon(TM)

chore: hide network select on add node

---

assets/locales/en/translation.json
src/main/ipc.ts
src/main/nodeManager.ts
src/main/preload.ts
src/renderer/Generics/redesign/Header/Header.tsx
src/renderer/Generics/redesign/Header/header.css.ts
src/renderer/Presentational/ModalManager/ModalManager.tsx
src/renderer/Presentational/ModalManager/NodeSettingsModal.tsx
src/renderer/Presentational/ModalManager/RemoveNodeModal.tsx
src/renderer/Presentational/ModalManager/ResetConfigModal.tsx
src/renderer/Presentational/ModalManager/modalUtils.tsx
src/renderer/Presentational/NodeSettings/NodeSettings.tsx
src/renderer/Presentational/NodeSettings/NodeSettingsWrapper.tsx
src/renderer/Presentational/ResetConfigModal/ResetConfigWrapper.tsx
src/renderer/__mocks__/custom-preload-mock.ts
src/renderer/preload.d.ts

- added remove node to menu button
- replaced remove node with reset to defaults within node settings
- adds new config keys found in spec JSON into existing user node configs without having to delete the node or reset settings

feat: [NIC-68] Remove node in menu and reset config to default

---

package.json
src/common/NodeSpecs/base/base-v1.0.0.json
src/common/NodeSpecs/op-geth/op-geth-v1.0.0.json
src/common/NodeSpecs/op-node/op-node-v1.0.0.json
src/common/nodeSpec.ts
src/main/files.ts
src/main/nodePackageManager.ts
src/main/podman/install/install.ts
src/main/util/nodeLogUtils.ts
src/renderer/Presentational/AddNode/AddNode.tsx
src/renderer/state/rpcExecuteTranslation.ts

copy static files from a node package spec to clients data dirs (op stack)
base node is working

feat: copy static files from a node package spec to clients data dirs (op stack). base

---

package.json
src/__tests__/node/parseNanoTimestamp.test.ts
src/__tests__/node/parsePodmanLogMetadata.test.ts
src/main/util/nodeLogUtils.ts

fix: podman log timestamp format on ubuntu

---

src/common/NodeSpecs/reth/reth-v1.0.0.json

Current fix doesn't fix reth for non-mainnet. Waiting on this for non-mainnet fix https://github.com/paradigmxyz/reth/issues/4945

fix: reth data dir

---

package.json

previously the description was duplicated and our website was to our github readme
now it is:
ps. no way to set the image :(

chore: update package details and deb metadata

---

src/common/NodeSpecs/README.md

chore: replace expired discord link

chore: replace expired discord link

---

package-lock.json
src/renderer/Generics/redesign/CopyButton/CopyButton.tsx
src/renderer/Generics/redesign/CopyButton/copyButton.css.ts
src/renderer/Generics/redesign/FloatingButton/FloatingButton.tsx
src/renderer/Generics/redesign/FloatingButton/floatingButton.css.ts
src/renderer/Generics/redesign/LogMessage/LogMessage.tsx
src/renderer/Generics/redesign/LogMessage/logMessage.css.ts
src/renderer/Presentational/NodeSettings/WalletSettings.css.ts
src/renderer/Presentational/NodeSettings/WalletSettings.tsx

Copy button functionality as mentioned in [#333(comment)](https://github.com/NiceNode/nice-node/pull/333#issuecomment-1767849825).
#346

Minor redesign for copy buttons

---

src/common/NodeSpecs/lighthouse/lighthouse-v1.0.0.json
src/main/podman/podman.ts

Added QUIC support for Lighthouse, mentioned on Reddit
https://lighthouse-blog.sigmaprime.io/Quic.html

feat: added QUIC support for Lighthouse

---

src/main/benchbuddy/runBenchmark.ts
src/main/ipc.ts
src/main/menu.ts
src/main/preload.ts
src/main/state/benchmark.ts
src/renderer/Generics/redesign/Icon/LoadingIcon.tsx
src/renderer/Generics/redesign/Icon/loadingIcon.css.ts
src/renderer/Presentational/SystemMonitor/Benchmarks.tsx
src/renderer/Presentational/SystemMonitor/SystemMonitor.tsx
src/renderer/__mocks__/custom-preload-mock.ts
src/renderer/preload.d.ts

Manually run a system benchmark and see the latest results in System Monitor

feat: manual system benchmarks

---

assets/locales/de/dialog.json
assets/locales/de/updater.json
assets/locales/en/dialog.json
assets/locales/en/updater.json
assets/locales/es/dialog.json
assets/locales/es/updater.json
assets/locales/fr/dialog.json
assets/locales/fr/updater.json
assets/locales/ja/dialog.json
assets/locales/ja/updater.json
assets/locales/ru/dialog.json
assets/locales/ru/updater.json
assets/locales/vi/dialog.json
assets/locales/vi/updater.json
assets/locales/zh/dialog.json
assets/locales/zh/updater.json
src/main/dialog.ts
src/main/i18nMain.ts
src/main/updater.ts

Translate pop-ups for accepting or rejecting updates and selecting folders

---

assets/locales/en/translation.json
src/main/ipc.ts
src/main/preload.ts
src/main/state/settings.ts
src/main/updater.ts
src/renderer/Presentational/ModalManager/PreferencesModal.tsx
src/renderer/Presentational/Preferences/Preferences.tsx
src/renderer/Presentational/Preferences/PreferencesWrapper.tsx
src/renderer/preload.d.ts

feat: opt-in to pre-release updates

---

src/common/NodeSpecs/nitro/nitro-v1.0.0.json
src/common/NodeSpecs/op-node/op-node-v1.0.0.json
src/main/util/nodeLogUtils.ts
src/renderer/Presentational/NodeScreen/NodeScreen.tsx

The Beacon RPC Endpoint is required moving forward to verify blobs. This PR fixes the recommended local endpoints

Fix: arbitrum and op init config

---

src/common/NodeSpecs/reth/reth-v1.0.0.json

Thanks to @fubuloubu for the idea! #507

chore: bump reth version to beta

---

package.json
release/app/package-lock.json
release/app/package.json

chore: bump 5.0.0-alpha

---

.github/workflows/e2e-test-mac.yml
.github/workflows/package.yml
.github/workflows/prod-publish.yml
.github/workflows/staging-publish.yml
.husky/pre-commit
biome.jsonc
src/common/NodeSpecs/erigon/erigon-v1.0.0.json
src/common/NodeSpecs/ethereum/ethereum-v1.0.0.json
src/common/NodeSpecs/geth/geth-v1.0.0.json
src/common/NodeSpecs/nimbus/nimbus-v1.0.0.json
src/common/node.ts
src/main/corsMiddleware.ts
src/main/files.ts
src/main/main.ts
src/main/nodeLibraryManager.ts
src/main/podman/install/install.ts
src/main/podman/podman.ts
src/renderer/Presentational/AddNodeStepper/mergeNodeRequirements.ts
src/renderer/assets/images/nodeBackgrounds/index.tsx
src/renderer/assets/images/nodeIcons/index.tsx

Feat: erigon client ethereum (#537)

---

src/main/podman/install/install.ts

https://github.com/containers/podman/releases/tag/v5.1.0

chore: podman 5.1.0

---

src/common/index.md
src/renderer/state/rpcExecuteTranslation.ts

fix: typos

---

assets/locales/en/windowMenu.json
src/main/menu.ts

feat: open logs folder from help menu

---

src/common/NodeSpecs/reth/notes.md

docs: update notes.md
